version: '3'
services:
  es-7.7.1-node-0:
    image: elasticsearch:7.7.1
    container_name: es-7.7.1-node-0
    privileged: true
    environment:
      - cluster.name=elasticsearch-cluster-7.7.0
      - node.name=node0
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es-7.7.1-node-0,es-7.7.1-node-1,es-7.7.1-node-2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node0:/usr/share/elasticsearch/7.7.1/data
      - ./logs/node0:/usr/share/elasticsearch/7.7.1/logs
    ports:
      - 9200:9200
      - 9300:9300
  es-7.7.1-node-1:
    image: elasticsearch:7.7.1
    container_name: es-7.7.1-node-1
    privileged: true
    environment:
      - cluster.name=elasticsearch-cluster-7.7.0
      - node.name=node1
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es-7.7.1-node-0,es-7.7.1-node-1,es-7.7.1-node-2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node1:/usr/share/elasticsearch/7.7.1/data
      - ./logs/node1:/usr/share/elasticsearch/7.7.1/logs
    ports:
      - 9201:9200
      - 9301:9300
  es-7.7.1-node-2:
    image: elasticsearch:7.7.1
    container_name: es-7.7.1-node-2
    privileged: true
    environment:
      - cluster.name=elasticsearch-cluster-7.7.0
      - node.name=node2
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es-7.7.1-node-0,es-7.7.1-node-1,es-7.7.1-node-2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node2:/usr/share/elasticsearch/7.7.1/data
      - ./logs/node2:/usr/share/elasticsearch/7.7.1/logs
    ports:
      - 9202:9200
      - 9302:9300